name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install pytest selenium

    - name: Run unit tests
      run: |
        pytest tests/test_database.py -v

    - name: Run Selenium tests
      run: |
        streamlit run app.py &
        sleep 10
        pytest tests/test_selenium.py -v

    - name: Build Docker image
      run: |
        docker build -t student-management-system .

    - name: Save Docker image as artifact
      uses: actions/upload-artifact@v4
      with:
        name: docker-image
        path: .